"""create users table

Revision ID: ba83275468b2
Revises: 0746e37f6bc8
Create Date: 2025-09-03 08:37:24.640162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba83275468b2'
down_revision: Union[str, Sequence[str], None] = '0746e37f6bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('role', sa.String(length=16), server_default='USER', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_hashed_password'), 'users', ['hashed_password'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_table('salts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('salt', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salts_id'), 'salts', ['id'], unique=False)
    op.create_index(op.f('ix_salts_user_id'), 'salts', ['user_id'], unique=False)
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.drop_index(op.f('ix_categories_public_id'), table_name='categories')
    op.create_index(op.f('ix_categories_public_id'), 'categories', ['public_id'], unique=True)
    op.add_column('todos', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_todos_public_id'), table_name='todos')
    op.create_index(op.f('ix_todos_public_id'), 'todos', ['public_id'], unique=True)
    op.create_index(op.f('ix_todos_owner_id'), 'todos', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'todos', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_index(op.f('ix_todos_owner_id'), table_name='todos')
    op.drop_index(op.f('ix_todos_public_id'), table_name='todos')
    op.create_index(op.f('ix_todos_public_id'), 'todos', ['public_id'], unique=False)
    op.drop_column('todos', 'owner_id')
    op.drop_index(op.f('ix_categories_public_id'), table_name='categories')
    op.create_index(op.f('ix_categories_public_id'), 'categories', ['public_id'], unique=False)
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.drop_index(op.f('ix_salts_user_id'), table_name='salts')
    op.drop_index(op.f('ix_salts_id'), table_name='salts')
    op.drop_table('salts')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_hashed_password'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
